Update gitaction-ci.yml

diff --git a/.github/workflows/gitaction-ci.yml b/.github/workflows/gitaction-ci.yml
--- a/.github/workflows/gitaction-ci.yml
+++ b/.github/workflows/gitaction-ci.yml
@@ -58,39 +58,33 @@ jobs:
 
       - name: Build and push images
         run: |
+          set -e  # 스크립트에서 오류 발생 시 중단
+          
           for service in nginx Tomcat; do
-            cd "./front-app-repo/$service"
+            cd "./front-app-repo/$service" || { echo "Service directory not found"; exit 1; }
+            
             for app in index main login order reservation reservationinfo signup; do
               if [ -d "$app" ]; then
-                cd "$app"
+                cd "$app" || { echo "App directory not found"; exit 1; }
                 echo "Building and pushing image for service: $app"
-
+                
                 # 리포지토리 이름
                 REPOSITORY_NAME="${{ secrets.AWS_ECR }}"
                 # 이미지 태그
                 IMAGE_TAG="$service-$app:${{ env.VERSION }}"
                 # 전체 이미지 이름
                 IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG"
-
+                
                 # Docker 이미지 빌드
                 docker build -t "$IMAGE_NAME" .
-                # 빌드가 성공했는지 확인
-                if [ $? -ne 0 ]; then
-                  echo "Docker build failed"
-                  exit 1
-                fi
                 
                 # Docker 이미지 푸시
                 docker push "$IMAGE_NAME"
-                # 푸시가 성공했는지 확인
-                if [ $? -ne 0 ]; then
-                  echo "Docker push failed"
-                  exit 1
-                fi
-                cd ..
+                cd .. || { echo "Failed to return to service directory"; exit 1; }
               else
                 echo "Directory $app does not exist"
               fi
             done
-            cd ../../
+            
+            cd ../../ || { echo "Failed to return to main directory"; exit 1; }
           done
